---
- name: Stop and disable {{ lb_name }}.service
  systemd:
    name: "{{ lb_name }}.service"
    enabled: false
    state: stopped

- name: Remove OpenShift 4 Loadbalancer SystemD service
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/sysconfig/{{ lb_name }}.env"
    - "/etc/systemd/system/{{ lb_name }}.service"

- debug:
    msg: "Podman will stay in the Host, Play with it! ;-)"