---

openshift_install_dir: "{{ playbook_dir }}/../{{ cluster_name }}"
ssh_public_key_location: /root/.ssh/id_rsa

vn_subnet: "192.168.50.0"
vn_name: "openshift-4-cluster"
vn_internal_domain: "compute.local"
vn_public_domain: "h42.openshift.pub"

listen_address: "{{ hostvars['localhost']['ansible_default_ipv4']['address'] }}"

master_count: "3"
compute_count: "3"

# reference to coreos qcow file
coreos_version: 42.80.20190801.0
coreos_image_location: /var/lib/libvirt/images/rhcos-{{ coreos_version }}-qemu.qcow2 
