- name: create route53 DNS records
  route53:
    state: present
    zone: "{{ public_domain }}"
    record: "{{ item }}.{{ cluster_name }}.{{ public_domain }}"
    type: A
    ttl: 120
    value: "{{hostvars['localhost']['ansible_default_ipv4']['address']}}"
    wait: yes
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  with_items:
  - api
  - '*.apps'
