- name: Info message
  debug:
    msg: 
      - "If you like to follow the installation run 'tail -f  {{ openshift_install_dir }}/.openshift_install.log' in a second terminal."
      - "For more details, conntect to the bootstrap node: ssh -l core {{ vn_subnet.split('.')[:3] | join('.')}}.2"

- name: Waiting bootstrap to complete
  command: "openshift-install wait-for bootstrap-complete --dir {{ openshift_install_dir }} --log-level debug"
  register: bootstrap_status
  retries: 60
  delay: 60
  until: bootstrap_status.rc == 0

- include: destroy-vm.yml
  vars:
    vm_instance_name: "{{ cluster_name }}-bootstrap"

- name: Waiting installation to complete
  command: "openshift-install wait-for install-complete --dir {{ openshift_install_dir }}"
  register: install_status
  retries: 60
  delay: 60
  until: install_status.rc == 0

- name: debug
  debug:
    var: install_status
- name: Cluster informations
  debug:
    msg: "{{ install_status.stderr_lines | map('regex_replace', 'level=info msg=\"(.*)\"', '\\1') | list }}"

