---
- name: Installing KVM Packages (OS Release == 7).
  yum:
    name:
      - "@virtualization-hypervisor"
      - "@virtualization-client"
      - "@virtualization-platform"
      - "@virtualization-tools"
      # ansible virt need lxml
      - python-lxml
      # ansible route53 need  python-boto
      - python-boto
      # ansible k8s need python2-openshift
      - python2-openshift
    state: present

# Update qemu to +2.4 because option fw_cfg added in 2.4 
#  "qemu-kvm: -fw_cfg: invalid option"
#  https://github.com/qemu/qemu/commit/81b2b81062612e
- name: Add repos centos-release-openstack-stein (OS Release == 7).
  yum:
    name: centos-release-openstack-stein
    state: present

- name: Disable all openstack repos except centos-qemu-ev (OS Release == 7).
  command: "yum-config-manager -q --disable centos-ceph-nautilus centos-nfs-ganesha28 centos-openstack-stein"

- name: Upgrade all packages, include update qemu-kvm to >2.4
# because we added repo centos-qemu-ev from openstack
  yum:
    name: '*'
    state: latest
