#!/usr/bin/env ansible-playbook
---
- hosts: localhost
  vars_files:
  - ../cluster.yml
  vars:
    ssh_public_key: "{{ lookup('file', '{{ ssh_public_key_location }}.pub') }}"
  gather_facts: false
  roles:
    - bind
    - loadbalancer
    - role: ign
      ign_ssh_public_key: "{{ ssh_public_key }}"
      ign_terraform_workdir: "{{ terraform_workdir }}"
