
- name: allow FORWARD for all guest network DNAT traffic
  iptables:
    chain: FORWARD
    match: state
    ctstate: NEW,RELATED,ESTABLISHED
    destination: "{{subnet}}.0/24"
    jump: ACCEPT
    comment: OCP - Allow all DNAT FORWARD to guest network

- name: allow FORWARD for all guest network DNAT traffic
  iptables:
    chain: FORWARD
    match: state
    ctstate: NEW,RELATED,ESTABLISHED
    destination: "{{subnet}}.0/24"
    jump: ACCEPT
    comment: OCP - Allow all DNAT FORWARD to guest network
- name: remove in virbr0 reject
  iptables:
    chain: FORWARD
    in_interface: virbr0
    jump: REJECT
    state: absent
- name: remove out virbr0 reject
  iptables:
    chain: FORWARD
    out_interface: virbr0
    jump: REJECT
    state: absent
- name: Persist iptables rules
  local_action:
    "shell iptables-save > /etc/sysconfig/iptables"
