
- name: install packages for RedHat or CentOS
  yum:
    name: "{{ packages_centos}}"
    state: latest
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'
- name: upgrade python pip
  command: pip install --upgrade pip
- name: install python boto
  command: pip install boto
- name: start libvirtd
  service:
    name: libvirtd
    enabled: yes
    state: started
  register: libvirtd
- name: Create new default pool
  command: "virsh pool-define-as --name {{ libvirt_storage_pool }} --type dir --target /var/lib/libvirt/images"
  when: libvirtd.changed
- name: Set autostart on pool default
  command: "virsh pool-autostart {{ libvirt_storage_pool }}"
  when: libvirtd.changed
- name: Start default pool
  command: "virsh pool-start {{ libvirt_storage_pool }}"
  when: libvirtd.changed
