- include: prepare-storage.yml
- include: kvm-packages.yml
- include: enable-nested-v.yml
- include: net-create-loop.yml
- include: enable-remote-virsh.yml
- include: prepare-terraformenv.yml
- name: upgrade redhat
  yum: name=* state=latest
