- name: create network
  virt_net:
    command: define
    name: "{{network}}"
    xml: "{{ lookup('file', '{{ playbook_dir }}/roles/kvm-host/files/{{ network }}.xml') }}"
- name: set nets as active
  virt_net:
    state: active
    name: "{{network}}"
- name: set autostart for all nets
  virt_net:
    autostart: yes
    name: "{{network}}"
