- name: Create a logical volume of 80%FREE
  lvol:
    vg: vg0
    lv: libvirt
    size: 80%FREE
    shrink: no
- name: Create files system to /dev/mapper/vg0-libvirt
  filesystem:
    fstype: xfs
    dev: /dev/mapper/vg0-libvirt
- name: Mount disk
  mount:
    path: /var/lib/libvirt/images
    src: "/dev/mapper/vg0-libvirt"
    fstype: xfs
    state: mounted
