

- name: Install Terraform Binary
  unarchive:
    src: "{{ terraform_url }}"
    dest: /usr/bin/
    remote_src: yes

- name: create Terraform workdir
  file:
    path: "{{ terraform_workdir }}"
    state: directory
    mode: '0755'

- name: Install Terraform Binary
  unarchive:
    src: "{{ terraform_url }}"
    dest: /usr/bin/
    remote_src: yes

- name: Get terraform-libvirt-provider
  copy:
    src: terraform-provider-libvirt
    dest: /usr/bin/terraform-provider-libvirt
    owner: root
    group: root
    mode: '0700'

- name: Create Terraform vars file
  template:
    src: cluster.tf.j2
    dest: "{{ terraform_workdir }}/cluster.tf"
  
- name: Create kube.tf file
  template:
    src: kube.tf.j2
    dest: "{{ terraform_workdir }}/kube.tf"

- name: Create variables.tf file
  template:
    src: variables.tf.j2
    dest: "{{ terraform_workdir }}/variables.tf"

- name: Create post instalation script
  template:
    src: post-terraform.sh.j2
    dest: "{{ terraform_workdir }}/post-terraform.sh"

- name: Install Openshift installer
  unarchive:
    src: "{{ ocpinstaller_url }}"
    dest: /usr/local/bin/
    remote_src: yes

- name: Install Openshift client
  unarchive:
    src: "{{ ocpclient_url }}"
    dest: /usr/local/bin/
    remote_src: yes
